min_number_loci: 5000
max_number_loci: 5000
nb_genes: 1
min_seed: 0
max_seed: 98745641
nb_seeds: 20
tree: "trees/MamGenTimescale.m.species.nwk"
bayes_inference: true
bayes_burn_in: 200
bayes_until: 500
simulators:
  neutral:
    model: "neutral"
  moving_optimum:
    model: "selection"
    peakness: 0.02
    epistasis: 2.0
    bias_optimum: 0.0
    sigma_optimum: 1.0
    theta_optimum: 0.0
  stabilizing:
    model: "selection"
    peakness: 0.02
    epistasis: 2.0
    bias_optimum: 0.0
    sigma_optimum: 1.0
    theta_optimum: 0.02
core:
  mutation_mean_effect_size: 1.0
  mutation_rate_per_loci_per_generation: 7.9e-5
  population_size: 50
  number_of_generations: 54000
  burn_in: 1000
heritability: 0.2